[package]
name = "aps"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aps_core = { path = "../aps_core" }
clap = { version = "4.0.32", features = ["derive"] }
codespan-reporting = "0.11.1"
